project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Research Beyond the Lab: Open Science and Research Methods for a Global Engineer"
  description: "Website for rbtl spring term 2024"
  site-url: "https://rbtl-fs24.github.io/website/"
  repo-url: "https://github.com/rbtl-fs24/website"
  search: false
  page-footer: 
    left: | 
        This course is offerd by the [Global Health Engineering group at ETH Zurich](https://ghe.ethz.ch/)
    right:
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch"
        aria-label: Email
      - icon: github
        href: https://github.com/rbtl-fs24/website
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#openwashdata-lobby:staffchat.ethz.ch
        aria-label: Matrix
  
  sidebar:
    background: "#C8CEF3"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/rbtl-fs24/
        text: "GitHub organization"
    contents: 
      - href: index.qmd
        text: Course Overview
      - href: calendar.qmd
        text: Course Calendar
      - text: "---"
      - section: "Module 01"
        href: modules/md-01.qmd
        contents:
          - href: assignments/md-01/am-01-1-github.qmd
            text: "am-01: GitHub Account"
          - href: assignments/md-01/am-01-2-posit.qmd
            text: "am-02: Posit Cloud"
          - href: assignments/md-01/am-01-4-github.qmd
            text: "am-03: GitHub PAT"
      - section: "Module 02"
        href: modules/md-02.qmd
        contents:
          - href: assignments/md-02/am-02-1-github.qmd
            text: "am-01: Git configuration"
          - href: assignments/md-02/am-02-2-data-visualisation.qmd
            text: "am-02: Data visualisation"
      - section: "Module 03"
        href: modules/md-03.qmd
      - section: "Module 04"
        href: modules/md-04.qmd
      - section: "Module 05"
        href: modules/md-05.qmd
      - section: "Module 06"
        href: modules/md-06.qmd
      - section: "Module 07"
        href: modules/md-07.qmd
      - section: "Module 08"
        href: modules/md-08.qmd
      - section: "Module 09"
        href: modules/md-09.qmd
      - section: "Module 10"
        href: modules/md-10.qmd
      - section: "Module 11"
        href: modules/md-11.qmd
      - section: "Module 12"
        href: modules/md-12.qmd
        
format:
  html:
    theme:
      light: [litera, theme.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="rbtl-fs24.github.io/website" src="https://plausible.io/js/script.js"></script>

execute: 
  freeze: auto

